production:
  secret_key_base: 
  
  # if you have a phpbb3 forum rss feed enter the uri here. Else comment it out in app/views/layout/application.html.haml
  forum_rss_uri: 'http://phpbb3for.um/syndication.php'
  
  #authorize boolean. Supply own auth-system if not using phpbb3
  authorize: false
  
  # team id aquired by going to your teams EAsports page view source and find club-id data in the iframe body.
  team_id: '12345'
  
  # team name is your teams name (Case sensitive)
  team_name: 'Example Team'


# fill in the other enviroments as needed following above guidlines 

test:
  secret_key_base: 
  forum_rss_uri: 
  team_id: 

development:
  secret_key_base: 
  forum_rss_uri: 
  authorize: true
  team_id: 
  team_name: 
