development:
  secret_key_base: '467fa7371abd49bee6dc248257fcd13cb51d521c2eb25c1d9cbcee1404a913561ae157f5806a3a7cdd381fcae52a1ed7f64eb292fc4693facf2448b99edff9d2'
  forum_rss_uri: 'http://bombers-hockey.com/forum/syndication.php'
  authorize: false
  team_id: '281934'
  team_name: 'Bombers Hockey'
  twitter_consumer_key: 'LESmeIMsMaqksIHUOoYaWhBJy'
  twitter_consumer_secret: 'MCJKbovuDqERIEdw42Kn29Cl6s7JkNYBms0wKNBzfF1Ep8PzUl'
  twitter_access_token: '2675242134-4aqgmZatKQUGOhHwEaR99RQx2UbPQHORojq3znA'
  twitter_access_token_secret: 'oomGyTsUZCGaVAYo4qHJ3nZTrPqQHNikP9C4TzLjpQA4r'

test:
  secret_key_base: '76e6abfa24e4af47c2d47602b047f37916b1fb3f7a912af883c7c3a89f68b927409cf2d34133c7b4d3f54d57741b2ab0d0bedc38f5bbac5c3148bbabcd5eae3b'
  forum_rss_uri: 'http://bombers-hockey.com/forum/syndication.php'
  team_id: '12345'

production:
  secret_key_base: 'ea90f50fccd935c28bbd9589585a884be5c4e12bf1add5cfbc1a4c8e870af7252c9b87db121f5724b12e92f5246070f37af1628e8e4628494b5d324a41e7c409'
  forum_rss_uri: 'http://bombers-hockey.com/forum/syndication.php'
  authorize: true
  team_id: '281934'
  team_name: 'Bombers Hockey'
